### ISSUE TITLE
academic calender

### ISSUE THREAD

**Issue by ghost** [frencojobs/uit-redesign#5]
(on academic calendar tab)

10 | 19.6.2019 | Educative Talk on Drug [Absue] & Essay Competition for Drug [Absue] Prevention
-- | -- | --
11 | 3.7.2019 | IT Business Plan Contest (UIT)
12 | 10.7.2019 | Debate Competition
13 | 12.7.2019 | The Myanmar & [Engligh] Essay Competition in Commemoration of the Martyrs' Day

: : words in [ ], u linked the academic calendar from the original site right?
well,the errors are in the original site

**Comment by frencojobs** [comment]
fixed this in b38079a62a20488a58853e07d68a51fc22109e01
